spring.application.name=uco-parking

spring.datasource.url=jdbc:postgresql://localhost:5432/ucoparking
spring.datasource.username=postgres
spring.datasource.password=miguelo74
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=ucoparking
spring.jpa.properties.hibernate.archive.scanner=org.hibernate.boot.archive.scan.internal.StandardScanner
